### ISSUE TITLE
[11. Test Database / 02. Isolated DB] solution causes errors when running `npx vitest` on Windows

### ISSUE THREAD

**Issue by wonu** [epicweb-dev/full-stack-testing#15]
Vitest either shows error messages like:
> Error: EBUSY: resource busy or locked, unlink 'C:\Users\wonu\Desktop\full-stack-testing\playground\tests\prisma\data.3.db'

or is terminated with panic error:
> thread '\<unnamed>' panicked at query-engine\query-engine-node-api\src\engine.rs:139:1

In my case, adding `await` keyword to `prisma.$disconnect()` in `playground/tests/setup/db-setup.ts` prevents errors.
On the other hand, `await` was not necessary when tested on WSL.

Although [the official docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#disconnect-1) instructs to call `$disconnect()` with `await`, I don't understand why there is this difference. :dizzy_face:

**Comment by kentcdodds** [comment]
The difference is that the `await` gives prisma a chance to completely unlock the database so other connections can proceed. The lack of `await` is a mistake and I'm pushing an update now. Thanks!
