### ISSUE TITLE
Error deletiing the profile pic

### ISSUE THREAD

**Issue by saurabhp75** [epicweb-dev/full-stack-testing#18]
In the final version of the workshop app, deleting the profile pic gives an error (Input not instance of File).

How to reproduce:

1. Run the workshop app (npm run start). 
2. Then go to the last excercise "11.3 Global Setup" (http://localhost:5639/11/03/problem). 
3. Now run the solution app from the "Solution" tab.
4. Login as user kody.
5. Go to "http://localhost:7103/settings/profile/photo" and try deleting the profile pic.
6. Deletion will fail, showing the error "Input not instance of File".

**Comment by kentcdodds** [comment]
Thanks for reporting this.

I've actually already fixed this in the Epic Stack and I guess I somehow missed it in the workshops.

As it doesn't affect any of the workshop exercises I think I'm going to leave it as-is to avoid changing too much from the videos. But I do plan to eventually update everything and at that point I'll make sure this is handled.

If you're interested, I solved this using [a union](https://github.com/epicweb-dev/epic-stack/blob/d5d0764aa95845d11bc70cc9f56b5f1a6416037f/app/routes/settings%2B/profile.photo.tsx#L42-L54) and adding a bit of logic in [`onValidate`](https://github.com/epicweb-dev/epic-stack/blob/d5d0764aa95845d11bc70cc9f56b5f1a6416037f/app/routes/settings%2B/profile.photo.tsx#L131-L138).

Thanks!
