### ISSUE TITLE
Links to the Playwright documentation aren't working

### ISSUE THREAD

**Issue by deanfields** [epicweb-dev/full-stack-testing#7]
Even though I can see in the README, that the links are present, when attempting to click on them in the app they don't go anywhere they all point to:

```<a href="/01">📜 Playwright Docs</a>``` (for example)

https://github.com/epicweb-dev/full-stack-testing/blame/e52aa96ce9368c64e269f6087b850a66acf3409c/exercises/01.e2e/README.mdx#L311-L316

**Comment by kentcdodds** [comment]
Thanks for letting me know! I fixed it. This should get the update for you:

```
npx kcdshop update
```
